### ISSUE TITLE
persistent_disk allow_executions ?

### ISSUE THREAD

**Issue by BernhardDenner** [cloudfoundry/bpm-release#112]
When setting `persistend_disk: true` in bpm.yml, the job automatically gets access to data directory at `/var/vcap/store/JOB`. However, this directory is mounted with a no exec option.

Is there a way to have the default data share with exec permissions enabled?

If I try to workaround that, with something like:

```
persistent_disk: false
additional_volumes:
- path: /var/vcap/store/JOB
  writable: true
  allow_executions: true
```

bpm stops with the error message `invalid volume path: /var/vcap/store/JOB cannot conflict with default job data or store directories`.
