### ISSUE TITLE
Allow collocated jobs to read indicators without also reading all of job credentials

### ISSUE THREAD

**Issue by xoebus** [cloudfoundry/bpm-release#122]
The Healthwatch Indicators team is allowing release authors to include an `indicators.yml` document in their release which can contain various interesting metrics and associated thresholds for use with release instrumentation. These documents are currently stored in `/var/vcap/jobs/JOB/config/indicators.yml` and the Healthwatch release has a read-only mount of `/var/vcap/jobs` so that it is able to read these indicator documents.

The pattern of the release author including this extra metadata in the job is pretty neat. It allows the release author to be the one to encode this information rather than foisting the responsibility onto the release deployer who may be far less knowledgeable about how the release should behave.

Unfortunately, due to the way that BOSH lays files out on disk and limitations in the expressiveness of BPM volume paths the mount path `/var/vcap/jobs` also allows the Healthwatch job access to all of the credentials of all co-located jobs. This is a risk that we'd like to avoid if at all possible.

### Globbing

BPM could allow volumes to have their path contain globs. The globs would be evaluated at job start time and then each match would be mounted as a separate volume.

``` yaml
processes:
- name: healthwatch
  ...
  unsafe:
    unrestricted_volumes:
    - path: /var/vcap/jobs/*/indicators/indicator.yml`
```

There are a few concerns I have with this:

* The actual set of paths which will be mounted is not determinable until runtime. This hampers static analysis of the `bpm.yml` configuration files.
* The number of resolved paths may (unintentionally) be very large which will cause a large number of bind mounts to be created. This may have adverse effects on the stability of the machine.
* It would be easy to accidentally include a path which should not be included with an overly inclusive glob.
* Should we allow double wildcard matches (`**`) to match against multiple layers?

### Restricted Custom Globbing

In order to counter some of the unpredictability of the above idea we could introduce a far more restrictive language for specifying these globs. For example:

``` yaml
processes:
- name: healthwatch
  ...
  unsafe:
    unrestricted_volumes:
    - path: /var/vcap/jobs/{{ sibling_job }}/indicators/indicator.yml
```

Since BPM already has knowledge of all of the other jobs on the system it could add a determinable list of volumes for each job on the system.

I think from a safety perspective I prefer this even if it's a little non-standard.

### BPM "Links"

This idea is growing on me but does encourage the anti-pattern of using the filesystem to share information.

``` yaml
processes:
- name: server
  ...
  paths:
    io.pivotal.healthwatch/indicators:
      path: /var/vcap/jobs/server/indicators
```

``` yaml
processes:
- name: healthwatch
  ...
  unsafe:
    consume_paths:
    - io.pivotal.healthwatch/indicators
```

This would then find all of the co-located jobs which expose an `io.pivotal.healthwatch/indicator` path and mount them into the job. If none exist, then none get mounted.

### `boshreflect`

A longer term idea which wouldn't rely on the filesystem at all would be some kind of API which local jobs could query to learn more about their environment and sibling jobs. This could be exposed over a Unix socket or the network (think like the IaaS metadata servers). Jobs could register structured information to share with querying jobs.

Given the size and scope of this idea I don't think we can reasonably get it done in a short time-frame. We'd like to get this done sooner rather than later so that the Healthwatch team can stop using this pattern before it is repeated in the next component which wants to allow release author metadata.

/cc @aramprice @coreyti @vreynolds @joerodriguez @jfmyers9
